defaults:
- data: cubicflux_1d
- model: hyperfluxfno
- training: default
- loss_fn: vanilla
- override hydra/launcher: submitit_slurm
- _self_

wandb_kwargs:
  entity: jhko725
  project: hyperfluxfno_revised
  
hydra:
  launcher: 
    timeout_min: 2400
    tasks_per_node: 1
    gpus_per_node: 1

gpu_id: "auto" # or integer
