context_size: 20
segment_length: 2
batch_size: 1024
max_steps: 1e6
optimizer:
  _target_: optax.adamw
  learning_rate: 1e-4
checkpoint_dir: ./checkpoints
checkpoint_name: ${..data.name}_lr=${.optimizer.learning_rate}