# Maybe separate out into loader config?
context_length: 20
batch_size: 1024
batches_per_load: 250
queue_capacity: 10

max_steps: 50000

optimizer:
  _target_: optax.adamw
  learning_rate:
    _target_: optax.schedules.warmup_cosine_decay_schedule
    init_value: 0.0
    peak_value: 1e-3
    warmup_steps: 5000
    decay_steps: 45000
    end_value: 0.0
checkpoint_dir: ./checkpoints