_target_: context_flux_no.models.multiphysics.DISCO
num_spatial_dims: ${..data.num_spatial_dims}
channels: ${..data.channels}
embedding_dim: 384
patch_size: 4
num_hypernet_blocks: 2
droppath: 0.1
num_hypernet_heads: 2
mlp_hidden_dim: 48
opnet_hidden_channels: 6
opnet_norm_groups: 3
boundary_condition: periodic
activation:
  _target_: hydra.utils.get_method
  path: jax.nn.gelu
rtol: 1e-4
atol: 1e-6
max_steps: 16
key:
  _target_: jax.random.key
  seed: 0