_target_: context_flux_no.models.multiphysics.DPOT
num_spatial_dims: ${..data.num_spatial_dims}
in_channels: ${..data.channels}
out_channels: ${..data.channels}
in_timesteps: ${..training.context_length}
grid_size: [100,]
patch_size: [4,]
embedding_dim: 512
max_frequency_modes: 12
fno_depth: 6
num_blocks: 8
hidden_dim_patch: ${.embedding_dim}
hidden_dim_fno: ${.embedding_dim}
hidden_dim_output: ${.embedding_dim}
activation:
  _target_: hydra.utils.get_method
  path: jax.nn.gelu
key:
  _target_: jax.random.key
  seed: 0