_target_: context_flux_no.models.multiphysics.HyperFluxFNO
num_spatial_dims: ${..data.num_spatial_dims}
in_channels: ${..data.channels}
in_timesteps: ${..training.context_length}
embedding_dim: 512
encoder_type: TRecViT
encoder_kwargs:
  grid_size: [100, ]
  patch_size: [4, ]
  depth: 3
  temporal_block_width: ${..embedding_dim}
  num_heads: 10
  mlp_hidden_dim: ${..embedding_dim}
depth: 4
frequency_modes: 10
lift_dim: 32
stencil_size: [2, 2]
width_lift: ${.lift_dim}
width_project: ${.lift_dim}
width_hyper: ${.embedding_dim}
blocks_hyper: 10
activation:
  _target_: hydra.utils.get_method
  path: jax.nn.gelu
stack_grid: true
hypernet_init: bias_hyperinit
key:
  _target_: jax.random.PRNGKey
  seed: 0