from collections.abc import Callable
from typing import Literal

import equinox as eqx
import jax
import jax.numpy as jnp
from jaxtyping import Array, Float, PRNGKeyArray

from context_flux_no.utils import is_floating_array, num_parameters


class HypernetworkHead[NN: eqx.Module](eqx.Module):
    """Hypernetwork head module for a prespecified target neural network model.

    The weights of the target networks are generated by applying a linear layer to the
    given input parameter vector. Therefore, this module is intended to be used after
    some hypernetwork body module that nonlinearly maps input data to a 1D vector of
    parameters first."""

    linears: list[eqx.nn.Linear | None]
    unflatten_fns: list[Callable[[Float[Array, " in_size"]], NN] | None]

    target_static: NN
    in_size: int = eqx.field(static=True)

    def __init__(
        self,
        in_size: int,
        target_network: NN,
        initialization: Literal["default", "bias-hyperinit"],
        *,
        key: PRNGKeyArray,
    ):
        """**Arguments**:

        - `in_size`: The input size. The input to the module should be a vector of shape
            `(in_size, )`.
        - `target_network`: The target network to generate the weights for. Should be a
            subclass of `equinox.Module` containing float/complex arrays as trainable
            parameters.
        - `initialization`: How to initialize the weights and bias of the linear layers.
            `default` uses the default initialization for the linear layer.
            `bias-hyperinit` uses the Bias-HyperInit algorithm from [1].
        - `key`: A `jax.random.PRNGKey` used to provide randomness for parameter
            initialisation. (Keyword only argument.)


        **References**:
        - [1] J. Beck et al. Hypernetworks in Meta-Reinforcement Learning. CoRL (2022).
        """
        keys = jax.random.split(key)
        self.in_size = in_size

        target_params, target_static = eqx.partition(
            target_network, eqx.is_inexact_array
        )
        self.target_static: NN = target_static

        linears = []
        unflatten_fns = []
        for target_, k in zip(eqx.partition(target_params, is_floating_array), keys):
            l, unflat_fn = self._make_linear_layer(target_, initialization, key=k)
            linears.append(l)
            unflatten_fns.append(unflat_fn)
        self.linears = linears
        self.unflatten_fns = unflatten_fns

    def _make_linear_layer(
        self,
        target: NN,
        initialization: Literal["default", "bias-hyperinit"],
        *,
        key: PRNGKeyArray,
    ) -> tuple[eqx.nn.Linear, Callable] | tuple[None, None]:
        num_params = num_parameters(target)
        if num_params == 0:
            return None, None
        else:
            params_flat, unflatten_fn = jax.flatten_util.ravel_pytree(target)
            linear = eqx.nn.Linear(
                in_features=self.in_size,
                out_features=num_params,
                dtype=params_flat.dtype,
                key=key,
            )
            if initialization == "bias-hyperinit":
                weight = jnp.zeros_like(linear.weight)
                bias = params_flat
                linear = eqx.tree_at(
                    lambda l: (l.weight, l.bias), linear, replace=(weight, bias)
                )
            return linear, unflatten_fn

    def __call__(
        self,
        input_: Float[Array, " in_size"],
        *,
        key: PRNGKeyArray | None = None,
    ) -> NN:
        """Given an input parameter of shape `(in_size, )`, generate the target network
        with parameters created by applying a linear layer to the input."""
        target_params = []
        for linear, unflatten_fn in zip(self.linears, self.unflatten_fns):
            if linear is not None:
                target_params.append(unflatten_fn(linear(input_)))
        return eqx.combine(self.target_static, *target_params)
